Repository wireapp/core-crypto, pull requests merged in 2022-08, with the labels that each got.

#82 fix: Updated RustCrypto dependencies to match hpke-rs requirements
  crypto-ffi/src/wasm.rs
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  mls-provider/src/crypto_provider.rs
Labels: dependencies, crypto/rng, housekeeping

#87 rename 'group_info' into 'public_group_state'
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/include/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/conversation/handshake.rs
  crypto/src/external_commit.rs
  crypto/src/test_utils.rs
Labels: api:breaking

#92 build(tooling): Added semver version bumper
  .github/workflows/rust.yml
  CHANGELOG.md
  CHANGELOG.tpl
  xtask/Cargo.lock
  xtask/Cargo.toml
  xtask/src/documentation/changelog.rs
  xtask/src/documentation/mod.rs
  xtask/src/main.rs
  xtask/src/release/bump.rs
  xtask/src/release/mod.rs
Labels: housekeeping, tooling

#93 chore: Release v0.3.1
  CHANGELOG.md
  CHANGELOG.tpl
  Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
Labels: dependencies, housekeeping

#90 Verify our operations are durable [CL-63]
  Cargo.toml
  crypto-attributes/Cargo.toml
  crypto-attributes/src/lib.rs
  crypto/Cargo.toml
  crypto/src/conversation/decrypt.rs
  crypto/src/conversation/durability.rs
  crypto/src/conversation/encrypt.rs
  crypto/src/conversation/handshake.rs
  crypto/src/conversation/merge.rs
  crypto/src/conversation/mod.rs
  crypto/src/conversation/renew.rs
  crypto/src/error.rs
  crypto/src/external_proposal.rs
  crypto/src/lib.rs
Labels: housekeeping, tooling

#89 feat: Adding a wrapper for the swift API and initial docs [CL-62]
  .gitignore
  README.md
  crypto-ffi/Makefile.toml
  crypto-ffi/README.md
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Package.swift
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/Tests/CoreCryptoTests/CoreCryptoTests.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/bindings/swift/lib/module.modulemap
  crypto-ffi/build.rs
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/uniffi.toml
Labels: documentation, target:ios
