Repository wireapp/core-crypto, pull requests merged in 2022-10, with the labels that each got.

#136 feat!: rename callback client_id_belongs_to_one_of
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/wasm.rs
  crypto/src/external_proposal.rs
  crypto/src/lib.rs
  crypto/src/test_utils.rs
Labels: api:breaking

#143 feat: validate received external commits
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/wasm.rs
  crypto/src/conversation/decrypt.rs
  crypto/src/conversation/handshake.rs
  crypto/src/error.rs
  crypto/src/external_commit.rs
  crypto/src/external_proposal.rs
  crypto/src/lib.rs
  crypto/src/test_utils.rs
Labels: enhancement

#144 build: fix compilation errors when building the project for wasm on macos
  interop/Cargo.toml
  interop/src/main.rs
Labels: target:wasm, housekeeping, tooling

#145 build: ensure all declared features used in isolation do not break compilation
  .github/workflows/rust.yml
Labels: housekeeping, tooling

#142 feat: Exporting secret key derived from the group and client ids from the members - CL-97 - CL-98
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/error.rs
  crypto/src/mls/conversation/export.rs
  crypto/src/mls/conversation/mod.rs
Labels: enhancement

#140 test: add fixtures for many ciphersuites
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/benches/create_group.rs
  crypto/benches/utils.rs
  crypto/src/mls/client.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/encrypt.rs
  crypto/src/mls/conversation/export.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/merge.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/renew.rs
  crypto/src/mls/credential.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/external_proposal.rs
  crypto/src/mls/member.rs
  crypto/src/mls/mod.rs
  crypto/src/mls/proposal.rs
  crypto/src/test_utils.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/fixtures.rs
  crypto/src/test_utils/mod.rs
  interop/src/clients/native.rs
  interop/src/main.rs
  keystore/tests/common.rs
Labels: enhancement, crypto/rng, housekeeping, tooling

#146 chore: Add support for Proteus within interop runner
  crypto-ffi/bindings/js/rollup.config.js
  crypto/src/lib.rs
  interop/Cargo.toml
  interop/src/build/web/cryptobox-esm/index.ts
  interop/src/build/web/cryptobox-esm/package.json
  interop/src/build/web/cryptobox-esm/tsconfig.json
  interop/src/build/web/cryptobox-esm/webpack.config.cjs
  interop/src/build/web/wasm.rs
  interop/src/build/web/webdriver.rs
  interop/src/clients/corecrypto/mod.rs
  interop/src/clients/corecrypto/native.rs
  interop/src/clients/corecrypto/web.rs
  interop/src/clients/cryptobox/mod.rs
  interop/src/clients/cryptobox/native.rs
  interop/src/clients/cryptobox/web.rs
  interop/src/clients/mod.rs
  interop/src/main.rs
Labels: tooling
