Repository wireapp/core-crypto, pull requests merged in 2022-09, with the labels that each got.

#110 fix: Fixed iOS SQLCipher salt handling within keychain [CL-84]
  keystore/Cargo.toml
  keystore/src/connection/platform/generic/mod.rs
  keystore/tests/general.rs
Labels: bug, target:ios

#107 feat!: 'commit_pending_proposals' now returns an optional CommitBundle
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/conversation/decrypt.rs
  crypto/src/conversation/handshake.rs
  crypto/src/external_proposal.rs
  crypto/src/proposal.rs
Labels: enhancement, api:breaking

#115 chore: Release v0.5.0
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#118 fix: Unreachable pub struct breaks docgen
  crypto/src/conversation/public_group_state.rs
Labels: bug, housekeeping

#119 fix: wee_alloc memory leak + NPM publish issue
  .github/workflows/publish.yml
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-ffi/Cargo.toml
  crypto-ffi/src/wasm.rs
Labels: bug, housekeeping

#120 chore: Update UniFFI to 0.20
  CHANGELOG.tpl
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/build.rs
Labels: bug, enhancement, target:ios, target:android, api:breaking

#121 chore: Release v0.5.0 Redux
  CHANGELOG.md
Labels: release

#123 fix: external_senders public key was not TLS deserialized
  crypto/src/conversation/mod.rs
  crypto/src/external_proposal.rs
Labels: bug

#112 chore: E2E testing Rust <=> WASM [CL-88]
  .github/workflows/docs.yml
  .github/workflows/publish.yml
  .github/workflows/rust.yml
  Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/src/wasm.rs
  crypto/src/conversation/commit_delay.rs
  extras/interop/src/main.rs
  extras/interop/src/wasm.setup.step1.js
  interop/Cargo.toml
  interop/README.md
  interop/src/build/mod.rs
  interop/src/build/web/mod.rs
  interop/src/build/web/wasm.rs
  interop/src/build/web/webdriver.rs
  interop/src/clients/android.rs
  interop/src/clients/ios.rs
  interop/src/clients/mod.rs
  interop/src/clients/native.rs
  interop/src/clients/web.rs
  interop/src/main.rs
  interop/src/util.rs
Labels: enhancement, target:wasm, housekeeping, tooling

#127 fix: TS Ciphersuite enum not correctly exported [CL-91]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
Labels: bug, target:wasm

#130 chore: Release v0.5.2
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#134 feat: add `clear_pending_group_from_external_commit` [CL-89]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/conversation/durability.rs
  crypto/src/external_commit.rs
Labels: enhancement
