Repository wireapp/core-crypto, pull requests merged in 2022-07, with the labels that each got.

#59 feat: Add ability to manually seed the PRNG entropy pool [CL-38]
  .github/workflows/rust.yml
  Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/include/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/generic/c_api/c_api_tests.rs
  crypto-ffi/src/generic/c_api/mod.rs
  crypto-ffi/src/generic/uniffi_support.rs
  crypto-ffi/src/wasm.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  keystore/Cargo.toml
  keystore/tests/common.rs
  keystore/tests/mls.rs
  mls-provider/Cargo.toml
  mls-provider/src/crypto_provider.rs
  mls-provider/src/error.rs
  mls-provider/src/lib.rs
  mls-provider/tests/crypto.rs
  mls-provider/tests/fixtures.rs
  mls-provider/tests/randomness.rs
  package.json
Labels: enhancement, target:ios, target:android, target:wasm, rust, crypto/rng

#60 docs: Improving docs of Core-Crypto - [CL-50]
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/client.rs
  crypto/src/conversation.rs
  crypto/src/credential.rs
  crypto/src/error.rs
  crypto/src/external_commit.rs
  crypto/src/external_proposal.rs
  crypto/src/lib.rs
  crypto/src/member.rs
  crypto/src/proposal.rs
  keystore/src/entities/mls.rs
  keystore/src/error.rs
  keystore/src/mls.rs
Labels: documentation

#52 feat: Implement KeyPackage pruning [CL-16] Redux
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/include/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/client.rs
  crypto/src/conversation.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  keystore/Cargo.toml
  keystore/src/connection/mod.rs
  keystore/src/connection/platform/wasm/mod.rs
  keystore/src/connection/platform/wasm/storage.rs
  keystore/src/entities/mod.rs
  keystore/src/entities/platform/generic/mls/group.rs
  keystore/src/entities/platform/generic/mls/identity.rs
  keystore/src/entities/platform/generic/mls/keypackage.rs
  keystore/src/entities/platform/generic/proteus/mod.rs
  keystore/src/entities/platform/wasm/mls/group.rs
  keystore/src/entities/platform/wasm/mls/identity.rs
  keystore/src/entities/platform/wasm/mls/keypackage.rs
  keystore/src/entities/platform/wasm/proteus/mod.rs
  keystore/src/error.rs
  keystore/src/mls.rs
  keystore/tests/common.rs
  keystore/tests/z_entities.rs
  mls-provider/tests/fixtures.rs
  mls-provider/tests/randomness.rs
Labels: bug, rust
