Repository wireapp/core-crypto, pull requests merged in 2023-02, with the labels that each got.

#236 chore: Added codecov settings
  codecov.yml
Labels: housekeeping, tooling

#239 chore: Release v0.6.0-rc.6
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#205 feat: Externally-generated clients [CL-130]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/error.rs
  crypto/src/mls/client.rs
  crypto/src/mls/mod.rs
Labels: enhancement, crypto/rng

#243 feat: Added support for Proteus Last Resort PreKeys [CL-132]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/proteus.rs
Labels: enhancement, target:ios, target:android, target:wasm, proteus

#247 fix: Proteus auto prekey might overwrite Last Resort prekey
  keystore/src/entities/proteus.rs
Labels: bug, proteus

#249 fix(wasm): Fall back on false when the callback doesn't retrurn a Promise
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/src/wasm.rs
Labels: bug, target:wasm

#253 chore: Release 0.6.1
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#254 fix(wasm): Fixed commitDelay being undefined when FFI says 0
  crypto-ffi/bindings/js/CoreCrypto.ts
Labels: bug, target:wasm

#256 chore: Release v0.6.2
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#260 chore: Bump webdriver version to 110
  extras/wasm-browser-run/src/webdriver.rs
Labels: dependencies
