Repository wireapp/core-crypto, pull requests merged in 2023-12, with the labels that each got.

#440 build: release v1.0.0-rc.20
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#439 feat!: canonicalize ClientId [WPB-5608]
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto/Cargo.toml
  crypto/src/e2e_identity/conversation_state.rs
  crypto/src/e2e_identity/id.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/e2e_identity/stash.rs
  crypto/src/mls/client/identifier.rs
  crypto/src/mls/client/mod.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/credential/mod.rs
  crypto/src/mls/credential/x509.rs
  crypto/src/mls/mod.rs
  crypto/src/proteus.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/mod.rs
  mls-provider/src/crypto_provider.rs
Labels: enhancement, api:breaking

#443 test: verify that clients can create conversation with x509 credentials
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/mod.rs
Labels: housekeeping

#445 fix: README mentions a task which doesn't exist
  README.md
Labels: documentation, housekeeping

#446 feat: handle refresh token [WPB-5012]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/crypto.rs
  crypto/src/e2e_identity/error.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/refresh_token.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/e2e_identity/stash.rs
  keystore/src/connection/platform/generic/migrations/V10__refresh_token.sql
  keystore/src/connection/platform/wasm/mod.rs
  keystore/src/entities/mls.rs
  keystore/src/entities/platform/generic/mls/mod.rs
  keystore/src/entities/platform/generic/mls/refresh_token.rs
  keystore/src/entities/platform/wasm/mls/mod.rs
  keystore/src/entities/platform/wasm/mls/refresh_token.rs
  keystore/src/error.rs
Labels: enhancement

#448 feat(e2ei)!: remove 'clientId' from activation & rotate enrollment
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/rotate.rs
Labels: enhancement, api:breaking

#449 release: v1.0.0-rc.22
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#455 feat!: remove PerDomainTrustAnchor extension altogether. Backward inc…
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/lib.rs
  crypto/src/mls/client/key_package.rs
  crypto/src/mls/conversation/config.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/leaf_node_validation.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/welcome.rs
  crypto/src/mls/credential/mod.rs
  crypto/src/mls/credential/trust_anchor.rs
  crypto/src/mls/external_commit.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/x509.rs
Labels: api:breaking, housekeeping, PR:EXTRA CAREFUL REVIEW
