Repository wireapp/core-crypto, pull requests merged in 2023-07, with the labels that each got.

#348 build: release 1.0.0-pre.6
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#349 feat!: catch duplicate messages [WPB-2788]
  crypto-ffi/src/CoreCrypto.udl
  crypto/src/error.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/duplicate.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/test_utils/fixtures.rs
Labels: enhancement, api:breaking

#356 chore: Release v1.0.0-pre.8
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/gradle.properties
  mls-provider/Cargo.toml
  package.json
Labels: release

#250 feat: Use -dalek fast proteus version [CL-123]
  Cargo.toml
  crypto/Cargo.toml
  crypto/src/error.rs
  crypto/src/proteus.rs
  interop/Cargo.toml
  keystore/Cargo.toml
  package.json
Labels: proteus

#346 feat: Include certificate roots and certificate policy in GroupContext - WPB-1188
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/error.rs
  crypto/src/lib.rs
  crypto/src/mls/conversation/config.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/welcome.rs
  crypto/src/mls/credential/mod.rs
  crypto/src/mls/credential/trust_anchor.rs
  crypto/src/mls/external_commit.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/mod.rs
  crypto/src/test_utils/x509.rs
Labels: enhancement
