Repository wireapp/core-crypto, pull requests merged in 2023-08, with the labels that each got.

#359 feat: Keystore Dump tooling [WPB-2261]
  Cargo.toml
  crypto/src/proteus.rs
  keystore-dump/Cargo.toml
  keystore-dump/src/main.rs
  keystore/Cargo.toml
  keystore/src/entities/mls.rs
  keystore/src/entities/mod.rs
  keystore/src/entities/platform/generic/mls/enrollment.rs
  keystore/src/entities/proteus.rs
  mls-provider/src/crypto_provider.rs
  mls-provider/src/lib.rs
Labels: tooling

#374 fix: reuse signature keypair for credential rotation [WPB-3294]
  crypto/src/e2e_identity/crypto.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/mls/client/identities.rs
  crypto/src/mls/client/key_package.rs
  crypto/src/mls/client/mod.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/credential/ext.rs
  crypto/src/test_utils/central.rs
  keystore-dump/src/main.rs
  keystore/src/connection/platform/generic/migrations/V5__created_at_credential.sql
  keystore/src/entities/mls.rs
  keystore/src/entities/platform/generic/mls/credential.rs
  keystore/src/entities/platform/generic/mls/signature_keypair.rs
  keystore/src/entities/platform/wasm/mls/credential.rs
  keystore/src/entities/platform/wasm/mls/signature_keypair.rs
  keystore/tests/mls.rs
  keystore/tests/z_entities.rs
Labels: bug

#385 fix: Make interop runner pick up CHROME_PATH from env
  interop/src/build/web/webdriver.rs
Labels: bug, housekeeping, tooling

#386 feat!: also restore buffered messages on the receiver side [WPB-3786]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/lib.rs
  crypto/src/mls/buffer_external_commit.rs
  crypto/src/mls/conversation/buffer_messages.rs
  crypto/src/mls/conversation/db_count.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/merge.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/credential/trust_anchor.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/external_proposal.rs
Labels: bug, enhancement, api:breaking

#384 fix!: UniFFI async cancellable routines
  .cargo/config.toml
  .gitignore
  crypto-ffi/Cargo.toml
  crypto-ffi/Makefile.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/ProteusClient.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/Uniffi.kt
  crypto-ffi/build.rs
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/generic/uniffi_support.rs
  crypto-ffi/src/lib.rs
  crypto-ffi/src/wasm.rs
Labels: bug, target:ios, target:android, api:breaking

#387 test: fix wasm test hitting a limit. Just split them for now, waiting for a proper solution
  .github/workflows/rust.yml
  crypto-ffi/bindings/js/test/wasm-tests.sh
Labels: bug, housekeeping, tooling

#391 fix: change e2ei enrollment identifier causing collisions
  crypto/src/e2e_identity/stash.rs
Labels: bug

#393 feat!: bump rusty-jwt-tools to v0.5.0
  Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/E2eiClient.kt
  crypto-ffi/bindings/jvm/src/test/kotlin/com/wire/crypto/client/E2EITest.kt
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/e2e_identity/types.rs
  crypto/src/mls/conversation/self_commit.rs
Labels: api:breaking, dependencies

#394 feat!: return raw PEM certificate in `getUserIdentities`
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/ByteUtils.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/mls/credential/ext.rs
  crypto/src/test_utils/central.rs
Labels: enhancement, api:breaking

#392 fix: Make UniFFI produce the correct symbol in bindings
  crypto-ffi/Cargo.toml
Labels: bug, target:ios, target:android, dependencies

#396 fix: UniFFI symbol matching
  .gitignore
  crypto-ffi/Cargo.toml
  crypto-ffi/Makefile.toml
  crypto-ffi/src/lib.rs
Labels: bug, target:ios, target:android, dependencies

#397 chore: Release v1.0.0-rc.10
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#398 fix!: UniFFI Errors
  .github/workflows/rust.yml
  .gitignore
  CHANGELOG.tpl
  Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/Makefile.toml
  crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto.xcodeproj/project.pbxproj
  crypto-ffi/bindings/swift/WireCoreCrypto/WireCoreCrypto/WireCoreCrypto.h
  crypto-ffi/src/generic.rs
  crypto-ffi/src/lib.rs
  crypto-ffi/uniffi.toml
  crypto/Cargo.toml
  crypto/src/e2e_identity/error.rs
  crypto/src/error.rs
  crypto/src/lib.rs
Labels: target:ios, target:android, api:breaking
