Repository wireapp/core-crypto, pull requests merged in 2023-03, with the labels that each got.

#263 feat!: Change proteus auto prekey return type to include prekey id [CL-143]
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/proteus.rs
Labels: api:breaking, proteus

#265 feat: Add ability to mark subconversations [CL-142]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/error.rs
  crypto/src/group_store.rs
  crypto/src/lib.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/durability.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/external_proposal.rs
  crypto/src/mls/mod.rs
  crypto/src/test_utils/mod.rs
  keystore/src/connection/platform/generic/migrations/V1__schema.sql
  keystore/src/connection/platform/generic/migrations/V2__proteus.sql
  keystore/src/connection/platform/generic/migrations/V3__parentgroups.sql
  keystore/src/entities/mls.rs
  keystore/src/entities/platform/generic/mls/group.rs
  keystore/src/entities/platform/generic/mls/pending_group.rs
  keystore/src/entities/platform/wasm/mls/group.rs
  keystore/src/mls.rs
  keystore/tests/z_entities.rs
Labels: enhancement

#271 fix(security): Fix rustsec advisories on xtask deps
  xtask/Cargo.lock
  xtask/Cargo.toml
Labels: dependencies

#270 fix: Exclude self from self-remove-commit delay [CL-144]
  crypto/src/mls/conversation/commit_delay.rs
  crypto/src/mls/conversation/decrypt.rs
Labels: enhancement, PR:EXTRA CAREFUL REVIEW

#272 feat(wasm): Added API to check the `Arc` strongref counter
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/src/wasm.rs
Labels: target:wasm

#275 fix: enable ios-wal-compat for iOS builds by default [CL-146]
  crypto/Cargo.toml
  mls-provider/Cargo.toml
Labels: target:ios

#276 chore: Android upgrade to NDK 25 + openssl android build fix [CL-147]
  .cargo/config.toml
  .github/workflows/bindings.yml
  .github/workflows/publish-android.yml
  crypto-ffi/Makefile.toml
Labels: target:android

#274 feat!: end-to-end identity API update
  Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/error.rs
  crypto/src/e2e_identity/mod.rs
  interop/src/clients/corecrypto/e2ei.js
Labels: enhancement

#278 fix!: Make FFI parameters compliant with rfc8555
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  interop/src/clients/corecrypto/e2ei.js
Labels: api:breaking

#281 chore: Release v0.7.0-rc.2
  .github/workflows/rust.yml
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/error.rs
  crypto/src/group_store.rs
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#282 fix: Proteus auto prekey ids not incrementing [CL-150]
  crypto/src/proteus.rs
  keystore/Cargo.toml
  keystore/src/entities/proteus.rs
  keystore/src/error.rs
Labels: bug, proteus

#283 chore: Release v0.7.0-rc.3
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#279 feat!: init MLS group with x509 certificate from e2e identity
  Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/benches/utils/mls.rs
  crypto/src/e2e_identity/crypto.rs
  crypto/src/e2e_identity/error.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/types.rs
  crypto/src/lib.rs
  crypto/src/mls/client.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/credential.rs
  crypto/src/mls/mod.rs
  crypto/src/proteus.rs
  crypto/src/test_utils/mod.rs
  interop/src/clients/corecrypto/e2ei.js
  interop/src/clients/corecrypto/native.rs
  interop/src/main.rs
Labels: enhancement, api:breaking

#286 fix: use schnellru fork for GroupStore faillible inserts [CL-151]
  Cargo.toml
  crypto/src/group_store.rs
Labels: bug

#285 build: uniffi 0.23
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/kt/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
Labels: target:ios, target:android, dependencies

#284 feat: copy/modify kotlin wrapper from Kalium
  .github/workflows/bindings.yml
  .github/workflows/publish-android.yml
  crypto-ffi/Makefile.toml
  crypto-ffi/bindings/kt/CoreCrypto.test.kt
  crypto-ffi/bindings/kt/CoreCrypto.test.kts
  crypto-ffi/bindings/kt/build.gradle.kts
  crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/kt/main/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/kt/main/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/kt/main/com/wire/crypto/client/ProteusClient.kt
  crypto-ffi/bindings/kt/main/com/wire/crypto/client/ProteusException.kt
  crypto-ffi/bindings/kt/test/com/wire/crypto/client/MLSClientTest.kt
  crypto-ffi/bindings/kt/test/com/wire/crypto/client/ProteusClientTest.kt
  crypto-ffi/build.rs
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
Labels: target:android
