Repository wireapp/core-crypto, pull requests merged in 2023-11, with the labels that each got.

#428 fix: Preserve schema upgrade path between schemafix'd versions and upcoming
  keystore/src/connection/platform/generic/migrations/V5__mls_draft_20.sql
Labels: bug

#429 chore: Release v1.0.0-rc.18
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
  xtask/Cargo.lock
  xtask/Cargo.toml
Labels: release

#432 feat!: e2ei changes [WPB-5470] [WPB-5473]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/e2e_identity/conversation_state.rs
  crypto/src/e2e_identity/device_status.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  crypto/src/mls/client/mod.rs
  crypto/src/mls/client/user_id.rs
  crypto/src/mls/conversation/export.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/mod.rs
  extras/wasm-browser-run/src/webdriver.rs
Labels: enhancement, api:breaking

#433 test: test DB migration from 0.9.2
  extras/keystore-regression-versions/cc-keystore-09/Cargo.toml
  extras/keystore-regression-versions/cc-keystore-09/src/main.rs
  extras/keystore-regression-versions/src/main.rs
Labels: housekeeping

#437 feat!: remove member from commit add
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/benches/commit.rs
  crypto/benches/create_group.rs
  crypto/benches/mls_proteus.rs
  crypto/benches/utils/mls.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  crypto/src/mls/buffer_external_commit.rs
  crypto/src/mls/client/user_id.rs
  crypto/src/mls/conversation/buffer_messages.rs
  crypto/src/mls/conversation/commit_delay.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/leaf_node_validation.rs
  crypto/src/mls/conversation/merge.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/orphan_welcome.rs
  crypto/src/mls/conversation/renew.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/conversation/welcome.rs
  crypto/src/mls/credential/mod.rs
  crypto/src/mls/credential/trust_anchor.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/member.rs
  crypto/src/mls/mod.rs
  crypto/src/test_utils/central.rs
  interop/src/clients/corecrypto/native.rs
  interop/src/clients/corecrypto/web.rs
  interop/src/clients/mod.rs
  interop/src/main.rs
Labels: enhancement, api:breaking
