Repository wireapp/core-crypto, pull requests merged in 2023-04, with the labels that each got.

#297 feat: decrypt messages returns identity
  Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/kt/main/com/wire/crypto/CoreCrypto.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/bindings/swift/Sources/CoreCryptoSwift/CoreCryptoSwift.swift
  crypto-ffi/bindings/swift/lib/core_cryptoFFI.h
  crypto-ffi/src/CoreCrypto.udl
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  crypto/src/mls/client.rs
  crypto/src/mls/conversation/commit_delay.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/handshake.rs
  crypto/src/mls/conversation/merge.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/renew.rs
  crypto/src/mls/credential.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/external_proposal.rs
  crypto/src/mls/member.rs
  crypto/src/mls/mod.rs
  crypto/src/mls/proposal.rs
  crypto/src/proteus.rs
  crypto/src/test_utils/central.rs
  crypto/src/test_utils/fixtures.rs
  crypto/src/test_utils/mod.rs
  interop/src/clients/corecrypto/e2ei.js
Labels: enhancement

#298 fix: Fixed iOS keychain handling with proper attributes [CL-157]
  keystore/Cargo.toml
  keystore/src/connection/platform/generic/mod.rs
Labels: bug, target:ios

#301 chore: Release v0.7.0
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  kotlin/android/build.gradle.kts
  kotlin/jvm/build.gradle.kts
  mls-provider/Cargo.toml
  package.json
Labels: release

#309 fix: typescript path has the wrong file extension
  package.json
Labels: target:wasm

#308 fix: native libraries not included in android package
  kotlin/android/build.gradle.kts
Labels: target:android
