Repository wireapp/core-crypto, pull requests merged in 2024-03, with the labels that each got.

#508 fix: Don't create an empty PKI env on restore [WPB-6905]
  crypto/src/e2e_identity/init_certificates.rs
  crypto/src/mls/mod.rs
  crypto/src/mls/restore.rs
  mls-provider/src/lib.rs
Labels: bug

#512 test: Add test to assert that revocation works properly
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/test_utils/mod.rs
  crypto/src/test_utils/x509.rs
  mls-provider/src/pki.rs
Labels: housekeeping, hardening

#511 test: Add test to assert that a basic client can join a verified conv…
  crypto/src/mls/credential/mod.rs
Labels: housekeeping, hardening

#513 fix: deduplicate CRL DPs
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/e2e_identity/init_certificates.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/mls/conversation/commit.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/proposal.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/conversation/welcome.rs
  crypto/src/mls/credential/crl.rs
  crypto/src/mls/external_commit.rs
  crypto/src/test_utils/x509.rs
Labels: bug, enhancement

#514 fix(web): Remove unique index on SignatureKeypair.pk
  crypto/src/mls/client/identities.rs
  crypto/src/mls/client/key_package.rs
  crypto/src/mls/conversation/commit.rs
  keystore/src/connection/platform/wasm/mod.rs
Labels: bug, enhancement

#519 build: Release v1.0.0-rc.50
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#521 fix: Various tweaks and fixes for revocation [WPB-6904]
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/CoreCryptoCentral.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/conversation_state.rs
  crypto/src/e2e_identity/device_status.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/init_certificates.rs
  crypto/src/e2e_identity/mod.rs
  keystore/src/entities/platform/wasm/mls/e2ei_acme_ca.rs
  package.json
Labels: bug

#522 build: Release v1.0.0-rc.51
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#524 fix: Correctly handle new CRL DPs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/proposal.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/conversation/welcome.rs
  crypto/src/mls/credential/crl.rs
  crypto/src/mls/external_commit.rs
Labels: bug

#525 build: Release v1.0.0-rc.52
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#526 fix: Correctly handle new CRL DPs in add_members
  crypto/src/mls/conversation/commit.rs
Labels: bug

#527 build: Release v1.0.0-rc.54
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#529 feat!: introduce `e2ei_verify_group_state` to preemptively check a group state through its GroupInfo before joining it
  crypto/src/e2e_identity/conversation_state.rs
Labels: enhancement

#528 feat!: WireIdentity works for Basic members [WPB-5975]
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/device_status.rs
  crypto/src/e2e_identity/identity.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/error.rs
  crypto/src/lib.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/mod.rs
  crypto/src/mls/conversation/self_commit.rs
  crypto/src/mls/credential/ext.rs
  crypto/src/mls/credential/typ.rs
  crypto/src/test_utils/central.rs
Labels: enhancement, api:breaking

#531 feat!: borrow enrollment instead of requiring ownership
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/e2e_identity/stash.rs
Labels: bug, api:breaking

#532 release: v1.0.0-rc.55
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release
