Repository wireapp/core-crypto, pull requests merged in 2024-02, with the labels that each got.

#487 fix: Allow revoked Credentials in MLS operations
  mls-provider/src/pki.rs
Labels: enhancement

#481 feat!: `clientPublicKey` now also works for x509 credentials
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MLSClient.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/mls/mod.rs
Labels: enhancement, api:breaking

#459 fix: verify group info
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/conversation_state.rs
  crypto/src/e2e_identity/rotate.rs
  crypto/src/mls/conversation/commit.rs
  crypto/src/mls/conversation/leaf_node_validation.rs
  crypto/src/mls/credential/mod.rs
  crypto/src/mls/external_commit.rs
  crypto/src/mls/external_proposal.rs
  crypto/src/test_utils/central.rs
  mls-provider/Cargo.toml
Labels: enhancement, hardening

#484 fix!: Add dedicated error for stale commits and proposals [WPB-6436]
  crypto/src/error.rs
  crypto/src/mls/conversation/commit.rs
  crypto/src/mls/conversation/decrypt.rs
  crypto/src/mls/conversation/duplicate.rs
  crypto/src/mls/conversation/proposal.rs
  crypto/src/mls/external_commit.rs
Labels: bug, enhancement, api:breaking, hardening

#485 e2ei nits
  crypto/src/e2e_identity/crypto.rs
  crypto/src/e2e_identity/rotate.rs
Labels: enhancement

#493 feat: add display name in dpop token
  Cargo.toml
  crypto/Cargo.toml
  crypto/src/e2e_identity/mod.rs
  mls-provider/Cargo.toml
Labels: enhancement, dependencies

#494 fix: Harden x509 validation & revocation checks
  crypto/src/e2e_identity/init_certificates.rs
  crypto/src/test_utils/x509.rs
Labels: bug, enhancement

#496 feat: add serialNumber, notBefore & notAfter in `WireIdentity` object
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/jvm/src/main/kotlin/com/wire/crypto/client/MlsModel.kt
  crypto-ffi/bindings/swift/Sources/CoreCrypto/CoreCrypto.swift
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/src/e2e_identity/device_status.rs
  crypto/src/e2e_identity/identity.rs
Labels: enhancement

#495 build: Release v1.0.0-rc.39
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#497 fix: TS mapping of identities was using experimental methods
  crypto-ffi/bindings/js/CoreCrypto.ts
Labels: bug

#499 fix: Integrate -pre version to iDB store version
  keystore/src/connection/platform/wasm/mod.rs
Labels: bug, target:wasm

#501 fix: Remove cached is_e2ei_capable flag
  crypto/src/e2e_identity/rotate.rs
  crypto/src/mls/client/mod.rs
Labels: bug

#502 build: Release v1.0.0-rc.41
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#503 fix: Prevent double-creating WASM stores
  extras/wasm-browser-run/Cargo.toml
  extras/wasm-browser-run/src/webdriver.rs
Labels: bug, target:wasm

#506 fix: only restore PKI env if client is e2ei capable.
  crypto/src/mls/mod.rs
Labels: bug
