Repository wireapp/core-crypto, pull requests merged in 2024-05, with the labels that each got.

#547 fix: Support legacy external senders with ECDSA
  crypto/src/mls/conversation/config.rs
Labels: bug

#548 build: Release v1.0.0-rc.59
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#549 fix: Ciphersuite being ignored on WASM createConversation
  crypto-ffi/src/wasm.rs
  crypto/src/mls/credential/ext.rs
  interop/src/clients/mod.rs
Labels: bug

#550 build: Release v1.0.0-rc.60
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#556 doc: document crates [wpb-9171]
  crypto-attributes/README.md
  crypto-ffi/README.md
  crypto/README.md
  keystore-dump/README.md
  mls-provider/README.md
Labels: documentation
