Repository wireapp/core-crypto, pull requests merged in 2024-04, with the labels that each got.

#534 fix: e2ei with NIST P-curves
  crypto/src/e2e_identity/crypto.rs
  crypto/src/e2e_identity/error.rs
  crypto/src/e2e_identity/mod.rs
  crypto/src/test_utils/fixtures.rs
  mls-provider/src/pki.rs
Labels: enhancement, crypto/rng

#535 feat: support JWK external sender [WPB-1193]
  crypto-ffi/src/generic.rs
  crypto-ffi/src/wasm.rs
  crypto/Cargo.toml
  crypto/src/mls/conversation/config.rs
  mls-provider/src/crypto_provider.rs
Labels: enhancement

#538 chore: Update deps
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
Labels: dependencies

#539 build: Release v1.0.0-rc.56
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#541 fix: Convert TS enums to their discriminant repr
  CHANGELOG.tpl
  crypto-ffi/bindings/js/CoreCrypto.ts
  crypto-ffi/bindings/js/test/CoreCrypto.test.js
Labels: bug, target:wasm

#542 build: Release v1.0.0-rc.57
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release

#545 fix: Avoid lock reentrancy on Generic FFI's conversation_create causing deadlocks [WPB-8949]
  crypto-ffi/src/generic.rs
Labels: bug

#546 build: Release v1.0.0-rc.58
  CHANGELOG.md
  CHANGELOG.tpl
  crypto-attributes/Cargo.toml
  crypto-ffi/Cargo.toml
  crypto-ffi/bindings/gradle.properties
  crypto/Cargo.toml
  interop/Cargo.toml
  keystore-dump/Cargo.toml
  keystore/Cargo.toml
  mls-provider/Cargo.toml
  package.json
Labels: release
